CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS field_definitions (
  id SERIAL PRIMARY KEY,
  field_name VARCHAR(100) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  field_type VARCHAR(50) NOT NULL,
  is_required BOOLEAN DEFAULT false,
  is_editable BOOLEAN DEFAULT true,
  field_order INTEGER DEFAULT 0,
  validation_rules JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS welds (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL,
  project_name VARCHAR(200),
  job_work_order VARCHAR(100),
  contractor VARCHAR(100),
  gps_location VARCHAR(100),
  report_number VARCHAR(100),
  weather VARCHAR(100),
  type_fit VARCHAR(100),
  wps VARCHAR(50),
  pipe_dia VARCHAR(50),
  grade_class VARCHAR(100),
  weld_number VARCHAR(50),
  welder VARCHAR(100),
  welder_stencil VARCHAR(50),
  first_ht_number VARCHAR(50),
  first_length VARCHAR(50),
  jt_number VARCHAR(50),
  second_ht_number VARCHAR(50),
  second_length VARCHAR(50),
  pre_heat VARCHAR(50),
  preheat_temperature VARCHAR(50),
  vt VARCHAR(50),
  process VARCHAR(100),
  nde_number VARCHAR(50),
  amps VARCHAR(100),
  volts VARCHAR(100),
  ipm VARCHAR(50),
  travel_speed VARCHAR(50),
  elapsed_time VARCHAR(50),
  electrode_type VARCHAR(100),
  electrode_size VARCHAR(50),
  electrode_manufacturer VARCHAR(100),
  cover_gas VARCHAR(100),
  flow_rate VARCHAR(50),
  weld_cap_height_1 VARCHAR(50),
  weld_cap_height_2 VARCHAR(50),
  weld_cap_height_3 VARCHAR(50),
  weld_cap_height_4 VARCHAR(50),
  weld_cap_height_5 VARCHAR(50),
  weld_cap_height_6 VARCHAR(50),
  root_pass_actual VARCHAR(50),
  root_pass_required VARCHAR(50),
  hot_pass_actual VARCHAR(50),
  hot_pass_required VARCHAR(50),
  fill_pass_actual VARCHAR(50),
  fill_pass_required VARCHAR(50),
  cap_pass_actual VARCHAR(50),
  cap_pass_required VARCHAR(50),
  top_actual VARCHAR(50),
  top_required VARCHAR(50),
  top_jt_no VARCHAR(50),
  top_wt_ut VARCHAR(50),
  top_heat_no VARCHAR(50),
  top_manufacturer VARCHAR(100),
  top_length VARCHAR(50),
  top_grade_class VARCHAR(100),
  top_seam_type VARCHAR(50),
  bottom_actual VARCHAR(50),
  bottom_required VARCHAR(50),
  bottom_jt_no VARCHAR(50),
  bottom_wt_ut VARCHAR(50),
  bottom_heat_no VARCHAR(50),
  bottom_manufacturer VARCHAR(100),
  bottom_length VARCHAR(50),
  bottom_grade_class VARCHAR(100),
  bottom_seam_type VARCHAR(50),
  welder_signature TEXT,
  inspector_signature TEXT,
  inspector_name VARCHAR(100),
  inspector_company VARCHAR(100),
  comments TEXT,
  image_path VARCHAR(500),
  custom_fields JSONB,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  status VARCHAR(50) DEFAULT 'active',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_welds (
  id SERIAL PRIMARY KEY,
  project_id INTEGER REFERENCES projects(id),
  weld_id INTEGER REFERENCES welds(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO field_definitions (field_name, display_name, field_type, is_required, field_order) VALUES
('date', 'Date', 'date', true, 1),
('project_name', 'Project Name', 'text', false, 2),
('job_work_order', 'Job/Work Order', 'text', false, 3),
('contractor', 'Contractor', 'text', false, 4),
('gps_location', 'GPS Location', 'text', false, 5),
('report_number', 'Report Number', 'text', false, 6),
('weather', 'Weather', 'text', false, 7),
('type_fit', 'Type/Fit', 'text', false, 8),
('wps', 'WPS', 'text', false, 9),
('pipe_dia', 'Pipe Diameter', 'text', false, 10),
('grade_class', 'Grade/Class', 'text', false, 11),
('weld_number', 'Weld #', 'text', false, 12),
('welder', 'Welder', 'text', false, 13),
('welder_stencil', 'Welder Stencil', 'text', false, 14),
('first_ht_number', '1st HT#', 'text', false, 15),
('first_length', '1st Length', 'text', false, 16),
('jt_number', 'JT#', 'text', false, 17),
('second_ht_number', '2nd HT#', 'text', false, 18),
('second_length', '2nd Length', 'text', false, 19),
('pre_heat', 'Pre Heat', 'text', false, 20),
('preheat_temperature', 'Preheat Temperature', 'text', false, 21),
('vt', 'VT', 'text', false, 22),
('process', 'Process', 'text', false, 23),
('nde_number', 'NDE#', 'text', false, 24),
('amps', 'Amps', 'text', false, 25),
('volts', 'Volts', 'text', false, 26),
('ipm', 'IPM', 'text', false, 27),
('travel_speed', 'Travel Speed', 'text', false, 28),
('elapsed_time', 'Elapsed Time', 'text', false, 29),
('electrode_type', 'Electrode Type', 'text', false, 30),
('electrode_size', 'Electrode Size', 'text', false, 31),
('electrode_manufacturer', 'Electrode Manufacturer', 'text', false, 32),
('cover_gas', 'Cover Gas', 'text', false, 33),
('flow_rate', 'Flow Rate', 'text', false, 34),
('weld_cap_height_1', 'Weld Cap Height 1', 'text', false, 35),
('weld_cap_height_2', 'Weld Cap Height 2', 'text', false, 36),
('weld_cap_height_3', 'Weld Cap Height 3', 'text', false, 37),
('weld_cap_height_4', 'Weld Cap Height 4', 'text', false, 38),
('weld_cap_height_5', 'Weld Cap Height 5', 'text', false, 39),
('weld_cap_height_6', 'Weld Cap Height 6', 'text', false, 40),
('root_pass_actual', 'Root Pass Actual', 'text', false, 41),
('root_pass_required', 'Root Pass Required', 'text', false, 42),
('hot_pass_actual', 'Hot Pass Actual', 'text', false, 43),
('hot_pass_required', 'Hot Pass Required', 'text', false, 44),
('fill_pass_actual', 'Fill Pass Actual', 'text', false, 45),
('fill_pass_required', 'Fill Pass Required', 'text', false, 46),
('cap_pass_actual', 'Cap Pass Actual', 'text', false, 47),
('cap_pass_required', 'Cap Pass Required', 'text', false, 48),
('top_actual', 'Top Actual', 'text', false, 49),
('top_required', 'Top Required', 'text', false, 50),
('top_jt_no', 'Top JT No', 'text', false, 51),
('top_wt_ut', 'Top WT/UT', 'text', false, 52),
('top_heat_no', 'Top Heat No', 'text', false, 53),
('top_manufacturer', 'Top Manufacturer', 'text', false, 54),
('top_length', 'Top Length', 'text', false, 55),
('top_grade_class', 'Top Grade/Class', 'text', false, 56),
('top_seam_type', 'Top Seam Type', 'text', false, 57),
('bottom_actual', 'Bottom Actual', 'text', false, 58),
('bottom_required', 'Bottom Required', 'text', false, 59),
('bottom_jt_no', 'Bottom JT No', 'text', false, 60),
('bottom_wt_ut', 'Bottom WT/UT', 'text', false, 61),
('bottom_heat_no', 'Bottom Heat No', 'text', false, 62),
('bottom_manufacturer', 'Bottom Manufacturer', 'text', false, 63),
('bottom_length', 'Bottom Length', 'text', false, 64),
('bottom_grade_class', 'Bottom Grade/Class', 'text', false, 65),
('bottom_seam_type', 'Bottom Seam Type', 'text', false, 66),
('inspector_name', 'Inspector Name', 'text', false, 67),
('inspector_company', 'Inspector Company', 'text', false, 68),
('comments', 'Comments', 'textarea', false, 69);
